### ISSUE TITLE
Policy on contributing

### ISSUE THREAD

**Issue by nohe427** [Esri/geoservices-ruby#5]
Is there a policy on contributing to this repository?

**Comment by ajturner** [comment]
Typical process on Github - pull requests are preferred. Tests are nascent but appreciated. 

License is Apache, so making sure contributions are under that license as well.

Anything else in particular?

**Comment by nohe427** [comment]
Just checking to see if there was any particular conventions you wanted followed with submitting PRs.  Thanks!

**Comment by ajturner** [comment]
Thanks for checking. Not at this point but we can work together on it as questions arise.
